version: '3'
services:
  mongo-app:
    image:  darsh007/hospital-management-system:0.0.1
    ports:
      - "8081:8081"
    networks:
      - dbj-network
    environment:
      spring.data.mongodb.uri: mongodb://mongo:27017/database
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.7
    ports:
      - "27017:27017"
    networks:
      - dbj-network
networks:
  dbj-network:
    driver: bridge